<?php

namespace AppBundle\Repository;

/**
 * CitaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitaRepository extends \Doctrine\ORM\EntityRepository
{
}
