<?php

namespace AppBundle\Repository;

/**
 * ImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenRepository extends \Doctrine\ORM\EntityRepository
{
}
